version: '3'
services:
  oap:
    image: apache/skywalking-oap-server:8.4.0-es6
    container_name: oap
    restart: always
    ports:
      - 11800:11800 # agent 上报数据 gRPC 端口
      - 12800:12800 # ui 读取数据 http 端口
  skywaling-ui:
    image: apache/skywalking-ui:8.4.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 8080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800